export const API_RESPONSE_MESSAGE = {
  LOGIN_SUCCESS: "Logged in successfully.",
  REGISTER_SUCCESS: "Registered successfully.",
  NOT_FOUND: "Requested resource not found.",
  INVALID_CREDENTIALS: "Invalid username or password.",
  UNAUTHORIZED_ACCESS: "Access denied.",
  TOKEN_EXPIRED: "Session expired. Please log in again.",
  PROFILE_UPDATED: "Profile updated.",
  PASSWORD_CHANGED: "Password changed.",
  EMAIL_VERIFIED: "Email verified.",
  EMAIL_NOT_FOUND: "Email not found.",
  ACCOUNT_LOCKED: "Account locked due to multiple failed attempts.",
  OPERATION_FAILED: "An error occurred. Try again later.",
  RECORD_LIST: "Record list.",
  RECORD_CREATED: "Record created.",
  RECORD_UPDATED: "Record updated.",
  RECORD_DELETED: "Record deleted.",
  RECORD_ALREADY_EXIST: "Record already exist.",
  BAD_REQUEST: "Bad request. Check parameters.",
  SERVER_ERROR: "Server error. Try again later.",
  FORGOT_PASSWORD: "Password reset link sent.",
  EMAIL_ALREADY_IN_USE: "Email already in use.",
  ACCOUNT_CREATED: "Account created. Verify your email.",
  RESET_PASSWORD_SUCCESS: "Password reset successfully.",
};
