export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Dashboard } from "./Dashboard";
export { default as Profile } from "./Profile";
export { default as Note } from "./notes/Note";
export { default as AddNote } from "./notes/AddNote";
export { default as EditNote } from "./notes/EditNote";
export { default as VoiceNotePage } from "./Voice/Page";
